# base site information
baseURL: https://zmsy.co/
title: zmsy.co

# custom parameters
params:
  AuthorName: Zach Morrissey
  AuthorEmail: zachjmorrissey+zmsy@gmail.com
  GithubUser: zmsy
  LinkedInUser: zmsyco
  TwitterHandle: _zmsy
  HowieInstagram: https://www.instagram.com/howiethesamoyed

menu:
  navigation:
    - home: /
    - blog: /blog
    - projects: /projects
    - about: /about

# site settings
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
googleAnalytics: UA-104524581-1
