name: Deploy to S3

on: push
  # push:
  #   branches:
  #     - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hugo Build
        run: hugo -v
        uses: klakegg/hugo:0.65.3-ext-alpine
      - name: Deploy to S3
        run: hugo -v deploy --minify --maxDeletes -1
        uses: klakegg/hugo:0.65.3-ext-alpine
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}