name: Build & Deploy to S3

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    container: klakegg/hugo:0.65.3-ext-alpine
    steps:
      - uses: actions/checkout@v1
      - name: Hugo Build
        run: hugo-official -v --minify 
      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        run: hugo-official -v deploy --maxDeletes -1 --invalidateCDN
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}