name: Deploy to S3

on: push

jobs:
  build:
    name: Build and Deploy
    runs-on: klakegg/hugo:0.65.3
    steps:
      - uses: actions/checkout@v1
      - name: Hugo Build
        run: hugo -v
      - name: Deploy to S3
        if: github.ref == 'refs/heads/master'
        run: hugo -v deploy --minify --maxDeletes -1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}